# Версия docker-compose
version: '2'
# Список наших сервисов (контейнеров)
services:
    nginx:
        container_name: nginx
        # используем последний стабильный образ nginx
        image: nginx:latest
        # маршрутизируем порты
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        # nginx должен общаться с php контейнером
        links:
            - php
        restart: always
    php:
        container_name: php-fpm
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
        restart: always
    mysql:
        container_name: mysql
        image: mysql:5.7
        ports:
            - "3307:3306"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./db/:/docker-entrypoint-initdb.d/
        restart: always
        # задаем пароль для root пользователя
        environment:
            MYSQL_ROOT_PASSWORD: secret
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        environment:
            ADMINER_DEFAULT_SERVER: mysql
